### ISSUE TITLE
Substantial scholarly effort: Does this submission meet the scope eligibility described in the JOSS guidelines

### ISSUE THREAD

**Issue by hechth** [nsviel/LidarSoft#2]
The minimum requirements are 3 full month work equivalents, which is not given in this case, as the repo contains 15 commits and is only about 1 month old.

**Comment by nsviel** [comment]
Thank you for your comment. Actually, I am working on this code since the last 3 years, but only in local. I released it just one or two months ago.

**Comment by hechth** [comment]
@nsviel Thank you for your comment and explanation! Would it be possible for you to give a rough timeline/overview of how you implemented things over time? With what did you start and what was added when etc.?

Maybe you could make this a small history/background section in the documentation?
